### ISSUE TITLE
Report not picking up Infernal Expansion mobs

### ISSUE THREAD

**Issue by pjlasl** [mactso/SpawnBalanceUtility#1]
I added Infernal Expansion to my modpack and ran the report. I do not see the mobs from this mod in your report, but I see others like Alex Mobs.

I guess I can manually add them to where I expect to see them, but it would be nice if your report picked them up.

Any ideas?

**Comment by mactso** [comment]
Hi!  same issue...

When you are adding a new mod to an existing set up, run SBU with *only* minecraft and the new mod and set SBU to suppress reporting minecraft mods.

**suppressMinecraftMobReporting = true**

That will give you a small BiomeMobWeight.txt file with only the new entries for that mod.
Add those lines to the end of your BiomeMobWeight.csv file.  The order in BiomeMobWeight.csv file doesn't matter.  The new BiomeMobWeight.txt will be sorted by Biome if you care (you can also sort in a spreadsheet).

So run Minecraft SBU, and Infernal Expansion only and you'll get this list... Just add it to the end of your existing BiomeMobWeight.csv file.

1, nether, minecraft:nether_wastes, MONSTER, infernalexp:voline, 50, 1, 3
2, nether, minecraft:soul_sand_valley, MONSTER, infernalexp:embody, 60, 1, 5
3, nether, minecraft:crimson_forest, MONSTER, infernalexp:shroomloin, 10, 1, 3
4, nether, minecraft:crimson_forest, MONSTER, infernalexp:voline, 10, 1, 5
5, nether, minecraft:warped_forest, MONSTER, infernalexp:warpbeetle, 10, 1, 1
6, nether, minecraft:basalt_deltas, MONSTER, infernalexp:basalt_giant, 30, 1, 1

Man-- those are pretty specialized!  
Cheers!
