### ISSUE TITLE
Third party downloads.

### ISSUE THREAD

**Issue by Explodey-Wolf** [mactso/SpawnBalanceUtility#11]
Hi, I'm posting this here as curseforge comments aren't working for me right now, but can you please enable third party launchers to download your modpack? It breaks all of the modpacks that have this mod. Thanks!

**Comment by mactso** [comment]
Hey man,

Right now we are holding off on that until we understand the implications better.   

We are focused on 19 and fabric now so there won't be a change to the setting for at least a couple months.

I'm hip deep in Harder Farther and helping a friend diagnosed with cancer a few weeks ago.

**Comment by mactso** [comment]
Okay, the mods will continue to be available free from Github.   You can build and distribute them to your friends.

We are going to use a mod supporter model for alternative mod loaders.   I'm in the process of setting up a patreon now.  We have one mod supported now- wireless speakers and the patron is choosing another low download mod to support now.

We'll be giving credit for supporting the mod on curseforge (unless you don't want credit).  As the mods pick up supporters, they'll become available for download elsewhere again.

Cheers,
Two Guys,
MacTso
