### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Looodon** [mactso/SpawnBalanceUtility#13]
Hey,
I frequently add and remove mods that add new mobs. The issue that I face is the mobs don't spawn because they aren't in the BiomeMobWeight.csv which doesn't automatically add them. I end up having to do everything all over from the beginning on excel. I think maybe a solution to that would be adding a config option to allow mobs not on the list to spawn anyway

Side question: does it matter the order of the code? Usually the first biome group is plains.. if i add a new mod and let the file regenerate, can i just paste the new rows into an old .csv out of order at the end of the file and just manually adding the row number in the beginning? 

It would look smth like this:
1. plains 
2. plains
3. plains
4. desert
5. desert
6. desert
7. taiga
8. taiga
9. taiga
10. plains (pasted in new mob)
11. taiga (pasted in new mob)
12. desert (pasted in new mob)

**Comment by mactso** [comment]
The way you and one new mod to an existing setup 
1) Set up a version with only minecraft and the new mod (or mods), this is *easy* with the curseforge installer.  I do it for testing.
2) Change the flag to suppress minecraft mob output.
3) run minecraft and exit- you'll have a tiny BiomeMobWeight.txt file with only stuff from that mod (or mods)
You'll end up with a file that has *only* the new mobs.  
4) You can paste that into your existing BiomeMobWeight.csv.
5) Sort it by biome ( if it matters )

I think the grouping matters but I'm not sure.  You could set up a test by splitting one biome (I use desert) into two groups with two obvious mobs (husks and skeletons or blazes).  Then see if one or both types of mobs spawn.
I *think* I tested this last year and I just pasted stuff to the end and it worked but I can't promise that.
