### ISSUE TITLE
Piglin Brute are falling from the sky 

### ISSUE THREAD

**Issue by MrMisit** [mactso/SpawnBalanceUtility#15]
Piglinbrutes are spawning in the air and falling down in the nether i have this problem in all netherbiomes disabling them in the config works for me but this has the bad side effect that they wont spawn anywhere in the nether. I have amplified nether installed which may be the reason for this to happen. Im playing on fabric version 1.19.2

Here is my full modlist:  - additionaladditions 5.1.0
	- adorn 3.7.0+1.19.2
	- advanced_runtime_resource_pack 0.6.2 via enhancedblockentities
	- adventurez 1.4.17
	- alternate-current 1.4.0
	- amecsapi 1.3.6+mc22w17a via backslot
	- amplifiednether 1.2
	- architects_palette 2.1.1
	- architectury 6.3.56
	- attributefix 17.1.2
	- autotag 2.0.0+1.19 via autotag-convention
	- autotag-convention 2.0.0+1.19
	- backslot 1.2.10
	- bclib 2.1.5
	- betteradvancements 0.2.2.142
	- betterbeds 1.2.0
	- betterdeserttemples 1.19.2-Fabric-2.1.1
	- betterdungeons 1.19.2-Fabric-3.1.1
	- betterend 2.1.2
	- bettermineshafts 1.19.2-Fabric-3.1.2
	- betternether 7.1.2
	- betteroceanmonuments 1.19.2-Fabric-2.0
	- betterstrongholds 1.19.2-Fabric-3.1.2
	- betterwitchhuts 1.19.2-Fabric-2.0.1
	- biomemakeover 1.19.2-1.6.2
	- blanket-client-tweaks 1.1.2
	- blossom 1.0.6
	- blue_endless_jankson 1.2.1 via t_and_t
	- bosses_of_mass_destruction 1.4.6-1.19.2
	- cacao 1.2
	- caffeineconfig 1.0.0+1.17 via sodium-extra
	- cardinal-components 5.0.2
	- cardinal-components-base 5.0.2 via cardinal-components
	- cardinal-components-block 5.0.2 via cardinal-components
	- cardinal-components-chunk 5.0.2 via cardinal-components
	- cardinal-components-entity 5.0.2 via cardinal-components
	- cardinal-components-item 5.0.2 via cardinal-components
	- cardinal-components-level 5.0.2 via cardinal-components
	- cardinal-components-scoreboard 5.0.2 via cardinal-components
	- cardinal-components-world 5.0.2 via cardinal-components
	- cave_enhancements 1.19.2-2.1.7-fabric
	- charm 4.4.4
	- charmonium 4.2.1
	- cinderscapes 3.0.3
	- cinderscapes-client 3.0.3 via cinderscapes
	- cinderscapes-common 3.0.3 via cinderscapes
	- cinderscapes-worldgen 3.0.3 via cinderscapes
	- clear-skies 2.0.95
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 8.2.88
	- collective 6.38
	- com_electronwill_night-config_core 3.6.6 via corgilib
	- com_electronwill_night-config_toml 3.6.6 via corgilib
	- com_eliotlash_mclib_mclib 20 via geckolib3
	- com_github_llamalad7_mixinextras 0.1.1 via zoomify
	- com_logisticscraft_occlusionculling 0.0.6-SNAPSHOT via entityculling
	- com_moandjiezana_toml_toml4j 0.7.2 via charm
	- com_sksamuel_scrimage_scrimage-core 4.0.31 via minelib
	- com_typesafe_config 1.4.1 via croptopia
	- com_velocitypowered_velocity-native 3.1.2-SNAPSHOT via krypton
	- conditional-mixin 0.3.0 via cull-less-leaves
	- continuity 2.0.1+1.19
	- corgilib 1.0.0.6
	- creeperoverhaul 2.0.3
	- croptopia 2.2.1
	- crowdin-translate 1.4+1.19 via durabilityviewer
	- ctov 3.1.4
	- cull-less-leaves 1.0.6
	- dark-loading-screen 1.6.12
	- debugify 2.7.1
	- dehydration 1.3.3
	- dev_isxander_settxi_settxi-core 2.10.5 via zoomify
	- dev_isxander_settxi_settxi-gui 2.10.5 via zoomify
	- dev_isxander_settxi_settxi-kotlinx-serialization 2.10.5 via zoomify
	- dragonloot 1.1.2
	- durabilityviewer 1.19.1-fabric0.58.5-1.10.3
	- dynamicfps 2.2.0
	- ecologics 2.1.11
	- eldritch_mobs 1.12.10
	- enderscape 0.4.1-1.19.2
	- enhancedblockentities 0.7.1+1.19
	- enhancedcelestials 2.1.0.2
	- entitycollisionfpsfix 2.0.0.0
	- entityculling 1.5.2-mc1.19
	- error_notifier 1.0.9 via roughlyenoughitems
	- expandeddelight 0.2.5.1
	- expert_armor 2.4
	- explorify-fabric 1.19-1.3.0
	- extended_armor_bars 1.2.1
	- extraalchemy 1.9.0
	- fabric-api 0.67.1+1.19.2
	- fabric-api-base 0.4.13+0d0f210290 via fabric-api
	- fabric-api-lookup-api-v1 1.6.12+93d8cb8290 via fabric-api
	- fabric-biome-api-v1 9.0.20+0d0f210290 via fabric-api
	- fabric-block-api-v1 1.0.1+12bfe4ea90 via fabric-api
	- fabric-blockrenderlayer-v1 1.1.22+c6af733c90 via fabric-api
	- fabric-client-tags-api-v1 1.0.3+b35fea8390 via fabric-api
	- fabric-command-api-v1 1.2.13+f71b366f90 via fabric-api
	- fabric-command-api-v2 2.1.9+93d8cb8290 via fabric-api
	- fabric-commands-v0 0.2.30+df3654b390 via fabric-api
	- fabric-containers-v0 0.1.37+df3654b390 via fabric-api
	- fabric-content-registries-v0 3.4.3+6064db2a90 via fabric-api
	- fabric-convention-tags-v1 1.1.3+93d8cb8290 via fabric-api
	- fabric-crash-report-info-v1 0.2.7+aeb40ebe90 via fabric-api
	- fabric-data-generation-api-v1 5.3.1+ad31814d90 via fabric-api
	- fabric-dimensions-v1 2.1.33+0d0f210290 via fabric-api
	- fabric-entity-events-v1 1.5.2+9244241690 via fabric-api
	- fabric-events-interaction-v0 0.4.30+c6af733c90 via fabric-api
	- fabric-events-lifecycle-v0 0.2.31+df3654b390 via fabric-api
	- fabric-game-rule-api-v1 1.0.23+c6af733c90 via fabric-api
	- fabric-item-api-v1 1.6.1+fa140d5990 via fabric-api
	- fabric-item-groups-v0 0.3.35+9244241690 via fabric-api
	- fabric-key-binding-api-v1 1.0.23+aaaf9d3390 via fabric-api
	- fabric-keybindings-v0 0.2.21+df3654b390 via fabric-api
	- fabric-language-kotlin 1.8.6+kotlin.1.7.21
	- fabric-lifecycle-events-v1 2.2.2+9244241690 via fabric-api
	- fabric-loot-api-v2 1.1.9+83a8659290 via fabric-api
	- fabric-loot-tables-v1 1.1.12+9e7660c690 via fabric-api
	- fabric-message-api-v1 5.0.5+93d8cb8290 via fabric-api
	- fabric-mining-level-api-v1 2.1.20+33fbc73890 via fabric-api
	- fabric-models-v0 0.3.19+c6af733c90 via fabric-api
	- fabric-networking-api-v1 1.2.7+9244241690 via fabric-api
	- fabric-networking-v0 0.3.24+df3654b390 via fabric-api
	- fabric-object-builder-api-v1 4.1.2+06e0e25190 via fabric-api
	- fabric-particles-v1 1.0.12+79adfe0a90 via fabric-api
	- fabric-registry-sync-v0 0.9.28+9244241690 via fabric-api
	- fabric-renderer-api-v1 1.0.14+12bfe4ea90 via fabric-api
	- fabric-renderer-indigo 0.6.16+aeb40ebe90 via fabric-api
	- fabric-renderer-registries-v1 3.2.22+df3654b390 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.17+0d0f210290 via fabric-api
	- fabric-rendering-fluids-v1 3.0.9+c6af733c90 via fabric-api
	- fabric-rendering-v0 1.1.25+df3654b390 via fabric-api
	- fabric-rendering-v1 1.11.1+73145abb90 via fabric-api
	- fabric-resource-conditions-api-v1 2.1.1+aae9039d90 via fabric-api
	- fabric-resource-loader-v0 0.8.1+0d0f210290 via fabric-api
	- fabric-screen-api-v1 1.0.29+0d0f210290 via fabric-api
	- fabric-screen-handler-api-v1 1.3.3+1cc24b1b90 via fabric-api
	- fabric-sound-api-v1 1.0.1+c4f28df590 via fabric-api
	- fabric-textures-v0 1.0.22+aeb40ebe90 via fabric-api
	- fabric-transfer-api-v1 2.1.3+9d081d6490 via fabric-api
	- fabric-transitive-access-wideners-v1 1.3.2+42d99c3290 via fabric-api
	- fabricenchantments 0.9.0
	- fabricloader 0.14.11
	- farmersdelight 1.19.2-1.3.9
	- ferritecore 5.0.3
	- fiber 0.23.0-2 via patchouli
	- frame 0.26.1+1.19-fabric
	- frame-api-base 0.2.1+906ebc04a9 via frame
	- frame-blocks-v0 0.1.3+233e7428a9 via frame
	- frame-config-v0 0.3.1+0fa45150a9 via frame
	- frame-content-registries-v0 0.4.0+2876b511a9 via frame
	- frame-enchantments-v0 0.1.0+4093105da9 via frame
	- frame-game-rules-v0 0.2.4+e7ce56a6a9 via frame
	- frame-items-v0 0.1.3+906ebc04a9 via frame
	- frame-loot-tables-v0 0.1.4+4f7341eca9 via frame
	- frame-registries-v0 0.1.1+0e0ec74ea9 via frame
	- frame-rendering-v0 0.1.5+906ebc04a9 via frame
	- frame-tabbed-item-groups-v0 0.2.4+0aca9b56a9 via frame
	- frame-toymaker-v0 0.6.1+b13741c3a9 via frame
	- frame-woods-v0 0.2.1+6a33fbada9 via frame
	- frycmobvariants 1.0.2+1.19.2
	- galosphere 1.19.2-1.2.1
	- gbfabrictools 1.3.4+1.19 via durabilityviewer
	- geckolib3 3.1.37
	- go-fish 1.6.0-1.19.1
	- graveyard 2.3
	- immersive_armors 1.5.3+1.19.2
	- imst 2.0.7
	- indium 1.0.9+mc1.19.2
	- ingredient-extension-api 3.0.6
	- inmis 2.7.0-1.19
	- io_github_douira_glsl-transformer 2.0.0-pre8 via iris
	- io_leangen_geantyref_geantyref 1.3.11 via croptopia
	- iris 1.5.0
	- itemmodelfix 1.0.3+1.19
	- jade 8.6.2
	- jankson 4.1.1+j1.2.1 via libgui
	- java 17
	- kirin 1.11.1 via presencefootsteps
	- krypton 0.2.1
	- kubejs 1902.6.0-build.135
	- lambdabettergrass 1.3.0+1.19
	- lambdynlights 2.1.2+1.19
	- lazydfu 0.1.3
	- libgui 6.0.0-beta.5+1.19-pre1 via additionaladditions
	- libninepatch 1.1.0 via libgui
	- lithium 0.10.3
	- lootjs 2.7.8
	- maelstrom_library 1.3-1.19-pre1 via bosses_of_mass_destruction
	- maybe-data 1.3.2-1.19-rc2 via wolveswitharmor
	- mcwbridges 2.0.5
	- mcwroofs 2.2.1
	- mcwwindows 2.1.2
	- memoryleakfix 1.19.1-0.7.0
	- midnightlib 0.6.0 via takesapillage
	- minecarttweaks 1.6
	- minecraft 1.19.2
	- minelib 0.1.3+1.19
	- missingwilds 1.1.2
	- mm 2.3 via enderscape
	- modmenu 4.0.6
	- moonlight 1.19.2-2.2.2
	- morebows 1.0.8+1.19.x
	- morejs 0.0.7
	- morevillagers 4.0.2
	- mousetweaks 2.22
	- multipart_entities 1.2-1.19-pre1 via bosses_of_mass_destruction
	- naturalist 2.1.1
	- nbttooltip 1.7.0
	- nyfsquiver Fabric-0.5.1-1.19.2
	- omega-config 1.2.3-1.18.1 via inmis
	- org_anarres_jcpp 1.4.14 via iris
	- org_antlr_antlr4-runtime 4.11.1 via iris
	- org_jetbrains_kotlin_kotlin-reflect 1.7.21 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.7.21 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.21 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.21 via fabric-language-kotlin
	- org_jetbrains_kotlinx_atomicfu-jvm 0.18.5 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.4.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.4.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.4.1 via fabric-language-kotlin
	- org_joml_joml 1.10.4 via sodium
	- org_spongepowered_configurate-core 4.1.2 via croptopia
	- org_spongepowered_configurate-hocon 4.1.2 via croptopia
	- owo 0.8.2+1.19 via woof
	- packet_tweaker 0.3.0+1.18.2 via server_translations_api
	- patchouli 1.19.2-76-FABRIC
	- polymer 0.2.18+1.19.2 via eldritch_mobs
	- polymer-blocks-ext 0.1.0-alpha.9+1.19.2 via eldritch_mobs
	- polymer-registry-sync-manipulator 0.0.3+1.19.2 via polymer
	- polymorph 0.46.0+1.19.2
	- presencefootsteps 1.6.2
	- pride 1.1.2+1.19 via lambdynlights
	- probablychests 0.5.5-1.19.2
	- reach-entity-attributes 2.3.0 via rottencreatures
	- reeses-sodium-options 1.4.7+mc1.19.2-build.59
	- resourcefullib 1.1.12 via spirit
	- rhino 1902.2.2-build.264
	- rottencreatures 1.0.1
	- roughlyenoughitems 9.1.587
	- server_translations_api 1.4.18+1.19.2 via eldritch_mobs
	- settxi-gui-yacl 2.10.5 via zoomify
	- sihywtcamd 1.7.1+1.19
	- sodium 0.4.4+build.18
	- sodium-extra 0.4.10+mc1.19.2-build.64
	- spawnbalanceutility 2
	- spectrelib 0.11.0+1.19 via polymorph
	- spirit 2.2.1
	- spruceui 4.0.0+1.19 via enhancedblockentities
	- starlight 1.1.1+fabric.ae22326
	- static-content 1.0.1-1.16.2 via wolveswitharmor
	- staticdata 1.1.2 via static-content
	- structory 1.0.1
	- supplementaries 1.19.2-2.2.45
	- t_and_t 1.10
	- takesapillage 1.0.3
	- terrablender 2.0.1.128 via terrestria
	- terraform-biome-remapper-api-v1 4.2.0 via terrestria
	- terraform-config-api-v1 4.2.0 via terrestria
	- terraform-dirt-api-v1 4.2.0 via terrestria
	- terraform-shapes-api-v1 4.2.0 via terrestria
	- terraform-surfaces-api-v1 4.2.0 via terrestria
	- terraform-tree-api-v1 4.2.0 via terrestria
	- terraform-wood-api-v1 4.2.0 via terrestria
	- terrestria 5.0.8
	- terrestria-client 5.0.8 via terrestria
	- terrestria-common 5.0.8 via terrestria
	- terrestria-worldgen 5.0.8 via terrestria
	- treeharvester 7.0
	- trinkets 3.4.1
	- twigs 2.0.0-beta.9+1.19-fabric
	- veinmining 1.0.0-beta.5+1.19.2
	- visuality 0.5.3
	- wardentools 2.1.2
	- wolveswitharmor 1.8.0-1.19
	- woof 3.0.0-1.19
	- xps 0.4.6-r+1.19.2-Fabric
	- xtraarrows 2.4.2
	- yet-another-config-lib 1.7.1
	- yungsapi 1.19.2-Fabric-3.6.1
	- yungsbridges 1.19.2-Fabric-3.0.1
	- yungsextras 1.19.2-Fabric-3.0.1
	- zoomify 2.9.0

and thank you for this great mod it makes handling mobspawns so easy and is a great help for me.

**Comment by mactso** [comment]
I'll look into this.   Have seen this with a couple mods that didn't have a spawn block but brutes shouldn't have that issue.   It'll probably be a few days - in the middle of bugs in another mod right now.

I'll update this when I know more- or by next week (even if it is only to say I don't know more yet).

Cheers,
MacTso

**Comment by mactso** [comment]
Oh, SBU basically is done running when the server comes up.   So the main issue is likely Brutes are spawning in Biomes their code may not be prepared to handle.

**Comment by mactso** [comment]
Okay, Brutes are *generated* not spawned and they do not have a SpawnPlacement.

I talked to my partner tonight and we might have a way to let you configure a list that SBU would register a mob for ground placement and to use Monster::checkMonsterSpawnRules.

eg...
      register(EntityType.TROPICAL_FISH, SpawnPlacements.Type.IN_WATER, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, TropicalFish::checkTropicalFishSpawnRules);
      register(EntityType.BAT, SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Bat::checkBatSpawnRules);
      register(EntityType.BLAZE, SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Monster::checkAnyLightMonsterSpawnRules);
      register(EntityType.CAVE_SPIDER, SpawnPlacements.Type.ON_GROUND, Heightmap.Types.MOTION_BLOCKING_NO_LEAVES, Monster::checkMonsterSpawnRules);

Example of such a list:
[Ground Mobs List : SBU will add an entry to SpawnPlacement.  Use for mobs spawning in the air]
"minecraft:brute"
"anotherguysfantasticmod:Madman"

FYI: Spawn Placement isn't checked for mobs from SpawnerCages

**Comment by mactso** [comment]
This feature is implemented for 1.16.5 and 1.19.X.
