### ISSUE TITLE
Report not picking up Creatures and Beasts mobs

### ISSUE THREAD

**Issue by pjlasl** [mactso/SpawnBalanceUtility#2]
Running the report does not pick up the mobs. If I add them to the new config option to include using a list, it also does not work.

I have to add them manually to the output.

**Comment by mactso** [comment]
Thanks for the report!

I gave their code a look and it seems pretty standard.  They are not requesting low priority so they are not going after.
This will take a deeper look.

**Comment by mactso** [comment]
Okay, I looked at it and here is the list

When you are adding a new mod to an existing set up, run SBU with *only* minecraft and the new mod and set SBU to suppress reporting minecraft mods.

**suppressMinecraftMobReporting = true**

That will give you a small BiomeMobWeight.txt file with only the new entries for that mod.
Add those lines to the end of your BiomeMobWeight.csv file.  The order in BiomeMobWeight.csv file doesn't matter.  The new BiomeMobWeight.txt will be sorted by Biome if you care (you can also sort in a spreadsheet).

1, nether, minecraft:basalt_deltas, MONSTER, cnb:cindershell, 10, 1, 2
2, nether, minecraft:basalt_deltas, MONSTER, cnb:hostile_sporeling, 10, 2, 4
3, swamp, minecraft:swamp, CREATURE, cnb:friendly_sporeling, 40, 3, 5
4, swamp, minecraft:swamp, CREATURE, cnb:lilytad, 35, 1, 1
5, mushroom, minecraft:mushroom_fields, CREATURE, cnb:friendly_sporeling, 40, 3, 5
6, nether, minecraft:nether_wastes, MONSTER, cnb:cindershell, 10, 1, 2
7, nether, minecraft:nether_wastes, MONSTER, cnb:hostile_sporeling, 10, 2, 4
8, taiga, minecraft:snowy_taiga_hills, CREATURE, cnb:yeti, 10, 2, 3
9, desert, minecraft:desert_hills, CREATURE, cnb:lizard, 50, 1, 4
10, river, minecraft:river, CREATURE, cnb:little_grebe, 30, 2, 3
11, nether, minecraft:soul_sand_valley, MONSTER, cnb:cindershell, 10, 1, 2
12, nether, minecraft:soul_sand_valley, MONSTER, cnb:hostile_sporeling, 10, 2, 4
13, taiga, minecraft:snowy_taiga, CREATURE, cnb:yeti, 10, 2, 3
14, river, minecraft:frozen_river, CREATURE, cnb:little_grebe, 30, 2, 3
15, mesa, minecraft:badlands, CREATURE, cnb:lizard, 50, 1, 4
16, nether, minecraft:warped_forest, MONSTER, cnb:cindershell, 10, 1, 2
17, nether, minecraft:warped_forest, MONSTER, cnb:neutral_sporeling, 10, 2, 4
18, icy, minecraft:snowy_tundra, CREATURE, cnb:yeti, 10, 2, 3
19, forest, minecraft:dark_forest, CREATURE, cnb:friendly_sporeling, 40, 3, 5
20, nether, minecraft:crimson_forest, MONSTER, cnb:cindershell, 10, 1, 2
21, nether, minecraft:crimson_forest, MONSTER, cnb:neutral_sporeling, 10, 2, 4
22, swamp, minecraft:swamp_hills, CREATURE, cnb:friendly_sporeling, 40, 3, 5
23, swamp, minecraft:swamp_hills, CREATURE, cnb:lilytad, 35, 1, 1
24, desert, minecraft:desert_lakes, CREATURE, cnb:lizard, 50, 1, 4
25, icy, minecraft:ice_spikes, CREATURE, cnb:yeti, 10, 2, 3
26, mesa, minecraft:wooded_badlands_plateau, CREATURE, cnb:lizard, 50, 1, 4
27, taiga, minecraft:snowy_taiga_mountains, CREATURE, cnb:yeti, 10, 2, 3
28, desert, minecraft:desert, CREATURE, cnb:lizard, 50, 1, 4
29, mushroom, minecraft:mushroom_field_shore, CREATURE, cnb:friendly_sporeling, 40, 3, 5
30, icy, minecraft:snowy_mountains, CREATURE, cnb:yeti, 10, 2, 3
31, mesa, minecraft:badlands_plateau, CREATURE, cnb:lizard, 50, 1, 4

**Comment by pjlasl** [comment]
I'll give it a try. Thank you!
