### ISSUE TITLE
[Suggestion] Serene Seasons support

### ISSUE THREAD

**Issue by MarioSMB** [mactso/SpawnBalanceUtility#8]
[Serene Seasons](https://www.curseforge.com/minecraft/mc-mods/serene-seasons) is a mod that adds seasons to the game, but one important thing has been lacking all this time - the ability to customise mob spawns per season (for example, spawning strays instead of skeletons during the winter at night).  
Support for controlling which season a mob can spawn in would be amazing, I hope it can be considered. Thank you.

**Comment by MarioSMB** [comment]
Thanks for responding, I've actually tried InControl in the past and ironically the exact function that may have allowed this has been disabled in their mod due to a Forge limitation!  

I understand if this is a little out of scope, here's hoping a means opens up someday to allow this kind of adjustment.  
Feel free to close this issue, thank you again for your consideration!

**Comment by mactso** [comment]
Okay.  It might be possible to write a specific mod that does this.   

Basically intercepts skeleton spawns and if some kind of winter hook exists and it's winter, then change the skeleton spawn to a stray spawn.

But it would be hard to integrate it with modded winter mobs.

**Comment by MarioSMB** [comment]
I'm not sure how early on seasons are loaded into the game, but would it possible make spawn listings bound to a specific season, similar to biomes?  
If that approach is possible it would fit right into this mod, though I'm not familiar with the loading system or Minecraft modding in general.
